import 'package:flutter/material.dart';

class AppColors {
  static const List<AccentColorOption> accentColors = [
    AccentColorOption(
      id: 'default_blue',
      name: 'Default Blue',
      nameHi: 'डिफ़ॉल्ट नीला',
      primary: Color(0xFF2196F3),
      primaryLight: Color(0xFF64B5F6),
      primaryDark: Color(0xFF1976D2),
      primaryContainer: Color(0xFFE3F2FD),
      onPrimaryContainer: Color(0xFF0D47A1),
    ),
    AccentColorOption(
      id: 'material_indigo',
      name: 'Material Indigo',
      nameHi: 'मटेरियल इंडिगो',
      primary: Color(0xFF3F51B5),
      primaryLight: Color(0xFF7986CB),
      primaryDark: Color(0xFF303F9F),
      primaryContainer: Color(0xFFE8EAF6),
      onPrimaryContainer: Color(0xFF1A237E),
    ),
    AccentColorOption(
      id: 'teal',
      name: 'Teal',
      nameHi: 'टील',
      primary: Color(0xFF0D9488),
      primaryLight: Color(0xFF2DD4BF),
      primaryDark: Color(0xFF115E59),
      primaryContainer: Color(0xFFF0FDFA),
      onPrimaryContainer: Color(0xFF134E4A),
    ),
    AccentColorOption(
      id: 'blue',
      name: 'Blue',
      nameHi: 'नीला',
      primary: Color(0xFF2563EB),
      primaryLight: Color(0xFF60A5FA),
      primaryDark: Color(0xFF1E40AF),
      primaryContainer: Color(0xFFEFF6FF),
      onPrimaryContainer: Color(0xFF1E3A8A),
    ),
    AccentColorOption(
      id: 'purple',
      name: 'Purple',
      nameHi: 'बैंगनी',
      primary: Color(0xFF7C3AED),
      primaryLight: Color(0xFFA78BFA),
      primaryDark: Color(0xFF5B21B6),
      primaryContainer: Color(0xFFF5F3FF),
      onPrimaryContainer: Color(0xFF4C1D95),
    ),
    AccentColorOption(
      id: 'rose',
      name: 'Rose',
      nameHi: 'गुलाबी',
      primary: Color(0xFFE11D48),
      primaryLight: Color(0xFFFB7185),
      primaryDark: Color(0xFF9F1239),
      primaryContainer: Color(0xFFFFF1F2),
      onPrimaryContainer: Color(0xFF881337),
    ),
    AccentColorOption(
      id: 'orange',
      name: 'Orange',
      nameHi: 'नारंगी',
      primary: Color(0xFFEA580C),
      primaryLight: Color(0xFFFB923C),
      primaryDark: Color(0xFFC2410C),
      primaryContainer: Color(0xFFFFF7ED),
      onPrimaryContainer: Color(0xFF9A3412),
    ),
    AccentColorOption(
      id: 'emerald',
      name: 'Emerald',
      nameHi: 'पन्ना',
      primary: Color(0xFF059669),
      primaryLight: Color(0xFF34D399),
      primaryDark: Color(0xFF047857),
      primaryContainer: Color(0xFFECFDF5),
      onPrimaryContainer: Color(0xFF065F46),
    ),
    AccentColorOption(
      id: 'amber',
      name: 'Amber',
      nameHi: 'एम्बर',
      primary: Color(0xFFD97706),
      primaryLight: Color(0xFFFBBF24),
      primaryDark: Color(0xFFB45309),
      primaryContainer: Color(0xFFFFFBEB),
      onPrimaryContainer: Color(0xFF92400E),
    ),
    AccentColorOption(
      id: 'cyan',
      name: 'Cyan',
      nameHi: 'सियान',
      primary: Color(0xFF0891B2),
      primaryLight: Color(0xFF22D3EE),
      primaryDark: Color(0xFF0E7490),
      primaryContainer: Color(0xFFECFEFF),
      onPrimaryContainer: Color(0xFF155E75),
    ),
    AccentColorOption(
      id: 'indigo',
      name: 'Indigo',
      nameHi: 'इंडिगो',
      primary: Color(0xFF4F46E5),
      primaryLight: Color(0xFF818CF8),
      primaryDark: Color(0xFF3730A3),
      primaryContainer: Color(0xFFEEF2FF),
      onPrimaryContainer: Color(0xFF312E81),
    ),
    AccentColorOption(
      id: 'pink',
      name: 'Pink',
      nameHi: 'गुलाबी',
      primary: Color(0xFFDB2777),
      primaryLight: Color(0xFFF472B6),
      primaryDark: Color(0xFFBE185D),
      primaryContainer: Color(0xFFFDF2F8),
      onPrimaryContainer: Color(0xFF9D174D),
    ),
    AccentColorOption(
      id: 'red',
      name: 'Red',
      nameHi: 'लाल',
      primary: Color(0xFFEF4444),
      primaryLight: Color(0xFFF87171),
      primaryDark: Color(0xFFB91C1C),
      primaryContainer: Color(0xFFFEF2F2),
      onPrimaryContainer: Color(0xFF7F1D1D),
    ),
    AccentColorOption(
      id: 'light_blue',
      name: 'Light Blue',
      nameHi: 'हल्का नीला',
      primary: Color(0xFF0EA5E9),
      primaryLight: Color(0xFF38BDF8),
      primaryDark: Color(0xFF0369A1),
      primaryContainer: Color(0xFFF0F9FF),
      onPrimaryContainer: Color(0xFF0C4A6E),
    ),
    AccentColorOption(
      id: 'lime',
      name: 'Lime',
      nameHi: 'लाइम',
      primary: Color(0xFF84CC16),
      primaryLight: Color(0xFFA3E635),
      primaryDark: Color(0xFF4D7C0F),
      primaryContainer: Color(0xFFECFCCB),
      onPrimaryContainer: Color(0xFF365314),
    ),
    AccentColorOption(
      id: 'violet',
      name: 'Violet',
      nameHi: 'बैंगनी',
      primary: Color(0xFF8B5CF6),
      primaryLight: Color(0xFFA78BFA),
      primaryDark: Color(0xFF5B21B6),
      primaryContainer: Color(0xFFF5F3FF),
      onPrimaryContainer: Color(0xFF4C1D95),
    ),
    AccentColorOption(
      id: 'fuchsia',
      name: 'Fuchsia',
      nameHi: 'फुकिया',
      primary: Color(0xFFD946EF),
      primaryLight: Color(0xFFE879F9),
      primaryDark: Color(0xFFA21CAF),
      primaryContainer: Color(0xFFFDF4FF),
      onPrimaryContainer: Color(0xFF701A75),
    ),
    AccentColorOption(
      id: 'slate',
      name: 'Slate',
      nameHi: 'स्लेट',
      primary: Color(0xFF64748B),
      primaryLight: Color(0xFF94A3B8),
      primaryDark: Color(0xFF334155),
      primaryContainer: Color(0xFFF8FAFC),
      onPrimaryContainer: Color(0xFF1E293B),
    ),
    AccentColorOption(
      id: 'zinc',
      name: 'Zinc',
      nameHi: 'जस्ता',
      primary: Color(0xFF71717A),
      primaryLight: Color(0xFFA1A1AA),
      primaryDark: Color(0xFF3F3F46),
      primaryContainer: Color(0xFFFAFAFA),
      onPrimaryContainer: Color(0xFF27272A),
    ),
    AccentColorOption(
      id: 'neutral',
      name: 'Neutral',
      nameHi: 'तटस्थ',
      primary: Color(0xFF737373),
      primaryLight: Color(0xFFA3A3A3),
      primaryDark: Color(0xFF404040),
      primaryContainer: Color(0xFFF5F5F5),
      onPrimaryContainer: Color(0xFF262626),
    ),
    AccentColorOption(
      id: 'stone',
      name: 'Stone',
      nameHi: 'पथरीला',
      primary: Color(0xFF78716C),
      primaryLight: Color(0xFFA8A29E),
      primaryDark: Color(0xFF44403C),
      primaryContainer: Color(0xFFF5F5F4),
      onPrimaryContainer: Color(0xFF292524),
    ),
    AccentColorOption(
      id: 'deep_orange',
      name: 'Deep Orange',
      nameHi: 'गहरा नारंगी',
      primary: Color(0xFFFF5722),
      primaryLight: Color(0xFFFF8A65),
      primaryDark: Color(0xFFE64A19),
      primaryContainer: Color(0xFFFBE9E7),
      onPrimaryContainer: Color(0xFFBF360C),
    ),
    AccentColorOption(
      id: 'brown',
      name: 'Brown',
      nameHi: 'भूरा',
      primary: Color(0xFF795548),
      primaryLight: Color(0xFFA1887F),
      primaryDark: Color(0xFF5D4037),
      primaryContainer: Color(0xFFEFEBE9),
      onPrimaryContainer: Color(0xFF3E2723),
    ),
    AccentColorOption(
      id: 'blue_grey',
      name: 'Blue Grey',
      nameHi: 'नीला भूरा',
      primary: Color(0xFF607D8B),
      primaryLight: Color(0xFF90A4AE),
      primaryDark: Color(0xFF455A64),
      primaryContainer: Color(0xFFECEFF1),
      onPrimaryContainer: Color(0xFF263238),
    ),
    AccentColorOption(
      id: 'light_green',
      name: 'Light Green',
      nameHi: 'हल्का हरा',
      primary: Color(0xFF8BC34A),
      primaryLight: Color(0xFFAED581),
      primaryDark: Color(0xFF689F38),
      primaryContainer: Color(0xFFF1F8E9),
      onPrimaryContainer: Color(0xFF33691E),
    ),
    AccentColorOption(
      id: 'deep_purple',
      name: 'Deep Purple',
      nameHi: 'गहरा बैंगनी',
      primary: Color(0xFF673AB7),
      primaryLight: Color(0xFF9575CD),
      primaryDark: Color(0xFF512DA8),
      primaryContainer: Color(0xFFEDE7F6),
      onPrimaryContainer: Color(0xFF311B92),
    ),
    AccentColorOption(
      id: 'melon',
      name: 'Melon',
      nameHi: 'तरबूज',
      primary: Color(0xFFFF6E40),
      primaryLight: Color(0xFFFF9E80),
      primaryDark: Color(0xFFFF3D00),
      primaryContainer: Color(0xFFFFEBE5),
      onPrimaryContainer: Color(0xFFDD2C00),
    ),
    AccentColorOption(
      id: 'sunshine',
      name: 'Sunshine',
      nameHi: 'धूप',
      primary: Color(0xFFFFD740),
      primaryLight: Color(0xFFFFE57F),
      primaryDark: Color(0xFFFFC400),
      primaryContainer: Color(0xFFFFF8E1),
      onPrimaryContainer: Color(0xFFFF8F00),
    ),
    AccentColorOption(
      id: 'mint',
      name: 'Mint',
      nameHi: 'पुदीना',
      primary: Color(0xFF69F0AE),
      primaryLight: Color(0xFFB9F6CA),
      primaryDark: Color(0xFF00E676),
      primaryContainer: Color(0xFFE0F2F1),
      onPrimaryContainer: Color(0xFF00695C),
    ),
    AccentColorOption(
      id: 'periwinkle',
      name: 'Periwinkle',
      nameHi: 'पेरिविंकल',
      primary: Color(0xFF7C4DFF),
      primaryLight: Color(0xFFB388FF),
      primaryDark: Color(0xFF651FFF),
      primaryContainer: Color(0xFFEDE7F6),
      onPrimaryContainer: Color(0xFF311B92),
    ),
    AccentColorOption(
      id: 'coral',
      name: 'Coral',
      nameHi: 'मूंगा',
      primary: Color(0xFFFF4081),
      primaryLight: Color(0xFFFF80AB),
      primaryDark: Color(0xFFF50057),
      primaryContainer: Color(0xFFFCE4EC),
      onPrimaryContainer: Color(0xFF880E4F),
    ),
    AccentColorOption(
      id: 'turquoise',
      name: 'Turquoise',
      nameHi: 'फ़िरोज़ा',
      primary: Color(0xFF40E0D0),
      primaryLight: Color(0xFFAFEEEE),
      primaryDark: Color(0xFF00CED1),
      primaryContainer: Color(0xFFE0F7FA),
      onPrimaryContainer: Color(0xFF006064),
    ),
    AccentColorOption(
      id: 'gold',
      name: 'Gold',
      nameHi: 'सोना',
      primary: Color(0xFFFFD700),
      primaryLight: Color(0xFFFFE4B5),
      primaryDark: Color(0xFFDAA520),
      primaryContainer: Color(0xFFFFFDE7),
      onPrimaryContainer: Color(0xFFF57F17),
    ),
    AccentColorOption(
      id: 'crimson',
      name: 'Crimson',
      nameHi: ' गहरा लाल',
      primary: Color(0xFFDC143C),
      primaryLight: Color(0xFFFF6B88),
      primaryDark: Color(0xFFC2185B),
      primaryContainer: Color(0xFFFCE4EC),
      onPrimaryContainer: Color(0xFF880E4F),
    ),
    AccentColorOption(
      id: 'lavender',
      name: 'Lavender',
      nameHi: 'लैवेन्डर',
      primary: Color(0xFF967BB6),
      primaryLight: Color(0xFFDCD0FF),
      primaryDark: Color(0xFF7B68EE),
      primaryContainer: Color(0xFFF3E5F5),
      onPrimaryContainer: Color(0xFF4A148C),
    ),
    AccentColorOption(
      id: 'salmon',
      name: 'Salmon',
      nameHi: 'सैमन',
      primary: Color(0xFFFA8072),
      primaryLight: Color(0xFFFFA07A),
      primaryDark: Color(0xFFE9967A),
      primaryContainer: Color(0xFFFBE9E7),
      onPrimaryContainer: Color(0xFFBF360C),
    ),
    AccentColorOption(
      id: 'royal_blue',
      name: 'Royal Blue',
      nameHi: 'शाही नीला',
      primary: Color(0xFF4169E1),
      primaryLight: Color(0xFF6495ED),
      primaryDark: Color(0xFF0000CD),
      primaryContainer: Color(0xFFE8EAF6),
      onPrimaryContainer: Color(0xFF1A237E),
    ),
    AccentColorOption(
      id: 'hot_pink',
      name: 'Hot Pink',
      nameHi: 'तेज गुलाबी',
      primary: Color(0xFFFF69B4),
      primaryLight: Color(0xFFFFB6C1),
      primaryDark: Color(0xFFC71585),
      primaryContainer: Color(0xFFFCE4EC),
      onPrimaryContainer: Color(0xFF880E4F),
    ),
    AccentColorOption(
      id: 'midnight_blue',
      name: 'Midnight Blue',
      nameHi: 'रात का नीला',
      primary: Color(0xFF191970),
      primaryLight: Color(0xFF483D8B),
      primaryDark: Color(0xFF000080),
      primaryContainer: Color(0xFFE8EAF6),
      onPrimaryContainer: Color(0xFF000051),
    ),
    AccentColorOption(
      id: 'forest_green',
      name: 'Forest Green',
      nameHi: 'वन हरा',
      primary: Color(0xFF228B22),
      primaryLight: Color(0xFF32CD32),
      primaryDark: Color(0xFF006400),
      primaryContainer: Color(0xFFE8F5E9),
      onPrimaryContainer: Color(0xFF1B5E20),
    ),
    AccentColorOption(
      id: 'steel_blue',
      name: 'Steel Blue',
      nameHi: 'स्टील नीला',
      primary: Color(0xFF4682B4),
      primaryLight: Color(0xFF87CEEB),
      primaryDark: Color(0xFF4169E1),
      primaryContainer: Color(0xFFE3F2FD),
      onPrimaryContainer: Color(0xFF0D47A1),
    ),
    AccentColorOption(
      id: 'olive',
      name: 'Olive',
      nameHi: 'जैतून',
      primary: Color(0xFF808000),
      primaryLight: Color(0xFF9ACD32),
      primaryDark: Color(0xFF556B2F),
      primaryContainer: Color(0xFFF9FBE7),
      onPrimaryContainer: Color(0xFF33691E),
    ),
    AccentColorOption(
      id: 'maroon',
      name: 'Maroon',
      nameHi: 'मरून',
      primary: Color(0xFF800000),
      primaryLight: Color(0xFFA52A2A),
      primaryDark: Color(0xFF4E0000),
      primaryContainer: Color(0xFFFCE4EC),
      onPrimaryContainer: Color(0xFF4A0000),
    ),
    AccentColorOption(
      id: 'aquamarine',
      name: 'Aquamarine',
      nameHi: 'एक्वामरीन',
      primary: Color(0xFF00BFA5),
      primaryLight: Color(0xFF1DE9B6),
      primaryDark: Color(0xFF00897B),
      primaryContainer: Color(0xFFE0F2F1),
      onPrimaryContainer: Color(0xFF004D40),
    ),
    AccentColorOption(
      id: 'chocolate',
      name: 'Chocolate',
      nameHi: 'चॉकलेट',
      primary: Color(0xFFD2691E),
      primaryLight: Color(0xFFF4A460),
      primaryDark: Color(0xFF8B4513),
      primaryContainer: Color(0xFFEFEBE9),
      onPrimaryContainer: Color(0xFF3E2723),
    ),
    AccentColorOption(
      id: 'sienna',
      name: 'Sienna',
      nameHi: 'गेरुआ',
      primary: Color(0xFFA0522D),
      primaryLight: Color(0xFFCD853F),
      primaryDark: Color(0xFF8B4513),
      primaryContainer: Color(0xFFD7CCC8),
      onPrimaryContainer: Color(0xFF3E2723),
    ),
    AccentColorOption(
      id: 'dark_slate_gray',
      name: 'Dark Slate Gray',
      nameHi: 'गहरा स्लेट ग्रे',
      primary: Color(0xFF2F4F4F),
      primaryLight: Color(0xFF5F9EA0),
      primaryDark: Color(0xFF203232),
      primaryContainer: Color(0xFFECEFF1),
      onPrimaryContainer: Color(0xFF102020),
    ),
    AccentColorOption(
      id: 'medium_slate_blue',
      name: 'Medium Slate Blue',
      nameHi: 'मध्यम स्लेट नीला',
      primary: Color(0xFF7B68EE),
      primaryLight: Color(0xFF9370DB),
      primaryDark: Color(0xFF483D8B),
      primaryContainer: Color(0xFFEDE7F6),
      onPrimaryContainer: Color(0xFF311B92),
    ),
    AccentColorOption(
      id: 'dark_violet',
      name: 'Dark Violet',
      nameHi: 'गहरा बैंगनी',
      primary: Color(0xFF9400D3),
      primaryLight: Color(0xFFBA55D3),
      primaryDark: Color(0xFF4B0082),
      primaryContainer: Color(0xFFF3E5F5),
      onPrimaryContainer: Color(0xFF4A148C),
    ),
    AccentColorOption(
      id: 'medium_orchid',
      name: 'Medium Orchid',
      nameHi: 'मध्यम आर्किड',
      primary: Color(0xFFBA55D3),
      primaryLight: Color(0xFFDA70D6),
      primaryDark: Color(0xFF8A2BE2),
      primaryContainer: Color(0xFFF3E5F5),
      onPrimaryContainer: Color(0xFF4A148C),
    ),
    AccentColorOption(
      id: 'plum',
      name: 'Plum',
      nameHi: 'बेर',
      primary: Color(0xFFDDA0DD),
      primaryLight: Color(0xFFEE82EE),
      primaryDark: Color(0xFF8B008B),
      primaryContainer: Color(0xFFFCE4EC),
      onPrimaryContainer: Color(0xFF4A148C),
    ),
    AccentColorOption(
      id: 'tomato',
      name: 'Tomato',
      nameHi: 'टमाटर',
      primary: Color(0xFFFF6347),
      primaryLight: Color(0xFFFF7F50),
      primaryDark: Color(0xFFCD5C5C),
      primaryContainer: Color(0xFFFBE9E7),
      onPrimaryContainer: Color(0xFFBF360C),
    ),
    AccentColorOption(
      id: 'orange_red',
      name: 'Orange Red',
      nameHi: 'नारंगी लाल',
      primary: Color(0xFFFF4500),
      primaryLight: Color(0xFFFF6F00),
      primaryDark: Color(0xFFBF360C),
      primaryContainer: Color(0xFFFFF3E0),
      onPrimaryContainer: Color(0xFFE65100),
    ),
    AccentColorOption(
      id: 'dark_khaki',
      name: 'Dark Khaki',
      nameHi: 'गहरा खाकी',
      primary: Color(0xFFBDB76B),
      primaryLight: Color(0xFFF0E68C),
      primaryDark: Color(0xFF808000),
      primaryContainer: Color(0xFFF9FBE7),
      onPrimaryContainer: Color(0xFF33691E),
    ),
    AccentColorOption(
      id: 'cornflower_blue',
      name: 'Cornflower Blue',
      nameHi: 'कॉर्नफ्लावर नीला',
      primary: Color(0xFF6495ED),
      primaryLight: Color(0xFF87CEEB),
      primaryDark: Color(0xFF4169E1),
      primaryContainer: Color(0xFFE3F2FD),
      onPrimaryContainer: Color(0xFF1565C0),
    ),
    AccentColorOption(
      id: 'dark_sea_green',
      name: 'Dark Sea Green',
      nameHi: 'गहरा समुद्री हरा',
      primary: Color(0xFF8FBC8F),
      primaryLight: Color(0xFF98FB98),
      primaryDark: Color(0xFF2E8B57),
      primaryContainer: Color(0xFFE8F5E9),
      onPrimaryContainer: Color(0xFF1B5E20),
    ),
    AccentColorOption(
      id: 'sandy_brown',
      name: 'Sandy Brown',
      nameHi: 'रेतीला भूरा',
      primary: Color(0xFFF4A460),
      primaryLight: Color(0xFFFFDAB9),
      primaryDark: Color(0xFFCD853F),
      primaryContainer: Color(0xFFFFF8E1),
      onPrimaryContainer: Color(0xFFE65100),
    ),
    AccentColorOption(
      id: 'rosy_brown',
      name: 'Rosy Brown',
      nameHi: 'गुलाबी भूरा',
      primary: Color(0xFFBC8F8F),
      primaryLight: Color(0xFFD2B48C),
      primaryDark: Color(0xFFA0522D),
      primaryContainer: Color(0xFFEFEBE9),
      onPrimaryContainer: Color(0xFF4E342E),
    ),
    AccentColorOption(
      id: 'pale_violet_red',
      name: 'Pale Violet Red',
      nameHi: 'हल्का बैंगनी लाल',
      primary: Color(0xFFDB7093),
      primaryLight: Color(0xFFFFB6C1),
      primaryDark: Color(0xFFC71585),
      primaryContainer: Color(0xFFFCE4EC),
      onPrimaryContainer: Color(0xFF880E4F),
    ),
    AccentColorOption(
      id: 'medium_aquamarine',
      name: 'Medium Aquamarine',
      nameHi: 'मध्यम एक्वामरीन',
      primary: Color(0xFF66CDAA),
      primaryLight: Color(0xFF7FFFD4),
      primaryDark: Color(0xFF20B2AA),
      primaryContainer: Color(0xFFE0F2F1),
      onPrimaryContainer: Color(0xFF00695C),
    ),
    AccentColorOption(
      id: 'cadet_blue',
      name: 'Cadet Blue',
      nameHi: 'कैडेट नीला',
      primary: Color(0xFF5F9EA0),
      primaryLight: Color(0xFF87CEEB),
      primaryDark: Color(0xFF4682B4),
      primaryContainer: Color(0xFFE0F7FA),
      onPrimaryContainer: Color(0xFF006064),
    ),
    AccentColorOption(
      id: 'dark_cyan',
      name: 'Dark Cyan',
      nameHi: 'गहरा सियान',
      primary: Color(0xFF008B8B),
      primaryLight: Color(0xFF20B2AA),
      primaryDark: Color(0xFF006060),
      primaryContainer: Color(0xFFE0F7FA),
      onPrimaryContainer: Color(0xFF006064),
    ),
    AccentColorOption(
      id: 'yellow_green',
      name: 'Yellow Green',
      nameHi: 'पीला हरा',
      primary: Color(0xFF9ACD32),
      primaryLight: Color(0xFFC0CA33),
      primaryDark: Color(0xFF689F38),
      primaryContainer: Color(0xFFF9FBE7),
      onPrimaryContainer: Color(0xFF33691E),
    ),
    AccentColorOption(
      id: 'chartreuse',
      name: 'Chartreuse',
      nameHi: 'हल्का पीला हरा',
      primary: Color(0xFF64DD17),
      primaryLight: Color(0xFF76FF03),
      primaryDark: Color(0xFF33691E),
      primaryContainer: Color(0xFFF1F8E9),
      onPrimaryContainer: Color(0xFF1B5E20),
    ),
    AccentColorOption(
      id: 'spring_green',
      name: 'Spring Green',
      nameHi: 'वसंत हरा',
      primary: Color(0xFF00C853),
      primaryLight: Color(0xFF69F0AE),
      primaryDark: Color(0xFF009624),
      primaryContainer: Color(0xFFE8F5E9),
      onPrimaryContainer: Color(0xFF1B5E20),
    ),
    AccentColorOption(
      id: 'medium_spring_green',
      name: 'Medium Spring Green',
      nameHi: 'मध्यम वसंत हरा',
      primary: Color(0xFF00FA9A),
      primaryLight: Color(0xFF00FF7F),
      primaryDark: Color(0xFF00C853),
      primaryContainer: Color(0xFFE0F2F1),
      onPrimaryContainer: Color(0xFF004D40),
    ),
    AccentColorOption(
      id: 'dodger_blue',
      name: 'Dodger Blue',
      nameHi: 'डॉजर नीला',
      primary: Color(0xFF1E90FF),
      primaryLight: Color(0xFF64B5F6),
      primaryDark: Color(0xFF0D47A1),
      primaryContainer: Color(0xFFE3F2FD),
      onPrimaryContainer: Color(0xFF0D47A1),
    ),
    AccentColorOption(
      id: 'deep_sky_blue',
      name: 'Deep Sky Blue',
      nameHi: 'गहरा आकाश नीला',
      primary: Color(0xFF00BFFF),
      primaryLight: Color(0xFF4FC3F7),
      primaryDark: Color(0xFF0288D1),
      primaryContainer: Color(0xFFE1F5FE),
      onPrimaryContainer: Color(0xFF01579B),
    ),
    AccentColorOption(
      id: 'sky_blue',
      name: 'Sky Blue',
      nameHi: 'आकाश नीला',
      primary: Color(0xFF0288D1),
      primaryLight: Color(0xFF4FC3F7),
      primaryDark: Color(0xFF01579B),
      primaryContainer: Color(0xFFE1F5FE),
      onPrimaryContainer: Color(0xFF01579B),
    ),
    AccentColorOption(
      id: 'light_sky_blue',
      name: 'Light Sky Blue',
      nameHi: 'हल्का आकाश नीला',
      primary: Color(0xFF03A9F4),
      primaryLight: Color(0xFF4FC3F7),
      primaryDark: Color(0xFF0277BD),
      primaryContainer: Color(0xFFE1F5FE),
      onPrimaryContainer: Color(0xFF01579B),
    ),
    AccentColorOption(
      id: 'navy',
      name: 'Navy',
      nameHi: 'नेवी',
      primary: Color(0xFF000080),
      primaryLight: Color(0xFF1A237E),
      primaryDark: Color(0xFF000051),
      primaryContainer: Color(0xFFE8EAF6),
      onPrimaryContainer: Color(0xFF000000),
    ),
    AccentColorOption(
      id: 'medium_blue',
      name: 'Medium Blue',
      nameHi: 'मध्यम नीला',
      primary: Color(0xFF0000CD),
      primaryLight: Color(0xFF4169E1),
      primaryDark: Color(0xFF00008B),
      primaryContainer: Color(0xFFE8EAF6),
      onPrimaryContainer: Color(0xFF1A237E),
    ),
    AccentColorOption(
      id: 'dark_blue',
      name: 'Dark Blue',
      nameHi: 'गहरा नीला',
      primary: Color(0xFF00008B),
      primaryLight: Color(0xFF0000CD),
      primaryDark: Color(0xFF000080),
      primaryContainer: Color(0xFFE8EAF6),
      onPrimaryContainer: Color(0xFF0D47A1),
    ),
  ];

  static const Color secondaryColor = Color(0xFFE11D48);
  static const Color secondaryLightColor = Color(0xFFFB7185);
  static const Color secondaryDarkColor = Color(0xFF9F1239);
  static const Color secondaryContainerColor = Color(0xFFFFF1F2);
  static const Color onSecondaryContainerColor = Color(0xFF881337);

  static const Color accentColor = Color(0xFFF59E0B);
  static const Color successColor = Color(0xFF10B981);
  static const Color warningColor = Color(0xFFF59E0B);
  static const Color errorColor = Color(0xFFEF4444);

  static const Color lightBackgroundColor = Color(0xFFF8FAFC);
  static const Color lightSurfaceColor = Color(0xFFFFFFFF);
  static const Color lightCardColor = Color(0xFFFFFFFF);
  static const Color lightOutlineColor = Color(0xFFE2E8F0);
  static const Color lightOutlineVariantColor = Color(0xFFF1F5F9);
  static const Color lightOnSurfaceColor = Color(0xFF0F172A);
  static const Color lightOnSurfaceVariantColor = Color(0xFF64748B);

  static const Color darkBackgroundColor = Color(0xFF0F172A);
  static const Color darkSurfaceColor = Color(0xFF1E293B);
  static const Color darkCardColor = Color(0xFF1E293B);
  static const Color darkOutlineColor = Color(0xFF334155);
  static const Color darkOutlineVariantColor = Color(0xFF475569);
  static const Color darkOnSurfaceColor = Color(0xFFF8FAFC);
  static const Color darkOnSurfaceVariantColor = Color(0xFF94A3B8);

  static AccentColorOption getColorById(String id) {
    return accentColors.firstWhere(
      (c) => c.id == id,
      orElse: () => accentColors.first,
    );
  }
}

class AccentColorOption {
  final String id;
  final String name;
  final String nameHi;
  final Color primary;
  final Color primaryLight;
  final Color primaryDark;
  final Color primaryContainer;
  final Color onPrimaryContainer;

  const AccentColorOption({
    required this.id,
    required this.name,
    required this.nameHi,
    required this.primary,
    required this.primaryLight,
    required this.primaryDark,
    required this.primaryContainer,
    required this.onPrimaryContainer,
  });

  String getLocalizedName(String languageCode) {
    return languageCode == 'hi' ? nameHi : name;
  }
}
